/*
  - Data made available by nodes that have already executed are available in the sharedState variable.
  - The script should set outcome to either "true" or "false".
 */
// Code Generated by Sidekick is for learning and experimentation purposes only.
// Get all entries from the managed user object

var queryFilter = "true"; // This returns all entries
//var params = {
  //  "_queryFilter": queryFilter
//};

//var response = openidm.query("managed/user", params);
  var widget = openidm.read("managed/alpha_user/" + "15053338-01c8-474b-8814-bfc9c17fd44f");
    if (widget) {
        logger.error("Printing widget"+ JSON.stringify(widget));
        logger.error("Printing widget 1" + widget);
    }
if (widget) {
    // Store the results in sharedState or transientState as needed
    //sharedState.put("allUsers", JSON.stringify(response.result));
    logger.error("Kavita's script printing allUsers");
    outcome = "true";
} else {

    logger.error("Kavita's script returned false");
    outcome = "false";
}


